const PEAKS_DATA = 
[
  {
    "id": 1,
    "alt": "Belmeken peak, 2626 m, Rila mountain, Bulgaria",
    "nameBg": "Белмекен",
    "nameEn": "Belmeken",
    "height": "2,626 m",
    "duration": "4–5 h",
    "distance": "10 km",
    "elevation": "+650 m",
    "summary": "A powerful ridge above Belmeken dam with wide alpine views and a calm introduction to Rila's high terrain. The ascent is steady and open, offering a sense of vast space and silence.",
    "final": false
  },
  {
    "id": 2,
    "alt": "Otovishki peak, 2696 m, Rila mountain, Bulgaria",
    "nameBg": "Отовишки връх",
    "nameEn": "Otovishki Peak",
    "height": "2,696 m",
    "duration": "6–7 h",
    "distance": "14 km",
    "elevation": "+1,100 m",
    "summary": "A rugged summit above Malyovitsa valley with dramatic rocky terrain and constant alpine exposure. The route feels remote and wild, with striking views of granite ridges.",
    "final": false
  },
  {
    "id": 3,
    "alt": "Kabul peak, 2531 m, Rila mountain, Bulgaria",
    "nameBg": "Кабул",
    "nameEn": "Kabul",
    "height": "2,531 m",
    "duration": "4–5 h",
    "distance": "11 km",
    "elevation": "+700 m",
    "summary": "A quieter peak with rolling alpine terrain and a softer rhythm than surrounding summits. It acts as a transitional climb between more demanding ridges.",
    "final": false
  },
  {
    "id": 4,
    "alt": "Popova Kapa peak, 2704 m, Rila mountain, Bulgaria",
    "nameBg": "Попова капа",
    "nameEn": "Popova Kapa",
    "height": "2,704 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A distinctive pyramidal summit with expansive views across central Rila. The climb is long but rewarding, emphasizing isolation and scale.",
    "final": false
  },
  {
    "id": 5,
    "alt": "Little Kupen peak, 2687 m, Rila mountain, Bulgaria",
    "nameBg": "Малък Купен",
    "nameEn": "Little Kupen",
    "height": "2,687 m",
    "duration": "5–6 h",
    "distance": "12 km",
    "elevation": "+900 m",
    "summary": "The beginning of the famous Kupen ridge, marked by steep granite and exposed sections. It introduces one of Rila's most technical alpine traverses.",
    "final": false
  },
  {
    "id": 6,
    "alt": "Middle Kupen peak, 2731 m, Rila mountain, Bulgaria",
    "nameBg": "Среден Купен",
    "nameEn": "Middle Kupen",
    "height": "2,731 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A sharp continuation of the Kupen ridge with sustained exposure and scrambling terrain. The views into deep cirques are constant and dramatic.",
    "final": false
  },
  {
    "id": 7,
    "alt": "Big Kupen peak, 2731 m, Rila mountain, Bulgaria",
    "nameBg": "Голям Купен",
    "nameEn": "Big Kupen",
    "height": "2,731 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "The highest of the Kupen trio, offering sustained ridge exposure and panoramic alpine scenery. A defining peak of central Rila.",
    "final": false
  },
  {
    "id": 8,
    "alt": "Angelov peak, 2643 m, Rila mountain, Bulgaria",
    "nameBg": "Ангелов връх",
    "nameEn": "Angelov Peak",
    "height": "2,643 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A rugged summit with calm surrounding ridgelines and wide views across Rila. It offers a balanced and accessible alpine experience.",
    "final": false
  },
  {
    "id": 9,
    "alt": "Big Bear peak, 2617 m, Rila mountain, Bulgaria",
    "nameBg": "Голям Мечит",
    "nameEn": "Big Bear Peak",
    "height": "2,617 m",
    "duration": "5–6 h",
    "distance": "12 km",
    "elevation": "+900 m",
    "summary": "A rounded summit overlooking vast valleys and glacial basins. The climb is moderate but highly rewarding in scenery.",
    "final": false
  },
  {
    "id": 10,
    "alt": "Pastri Slap peak, 2730 m, Rila mountain, Bulgaria",
    "nameBg": "Пъстри Слап",
    "nameEn": "Pastri Slap",
    "height": "2,730 m",
    "duration": "7–8 h",
    "distance": "15 km",
    "elevation": "+1,200 m",
    "summary": "A long and demanding route across broken terrain and shifting alpine views. The journey itself is the main reward.",
    "final": false
  },
  {
    "id": 11,
    "alt": "Small Mermer peak, 2702 m, Rila mountain, Bulgaria",
    "nameBg": "Малък Мермер",
    "nameEn": "Small Mermer",
    "height": "2,702 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A rocky peak in a complex granite landscape with wild terrain and constant variation. The climb requires focus and steady movement.",
    "final": false
  },
  {
    "id": 12,
    "alt": "Pavlev peak, 2668 m, Rila mountain, Bulgaria",
    "nameBg": "Павлев връх",
    "nameEn": "Pavlev Peak",
    "height": "2,668 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A balanced summit with open views and a feeling of deep wilderness. It connects naturally to surrounding ridges.",
    "final": false
  },
  {
    "id": 13,
    "alt": "Black Meadow peak, 2716 m, Rila mountain, Bulgaria",
    "nameBg": "Черна поляна",
    "nameEn": "Black Meadow",
    "height": "2,716 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A dark, open landscape surrounded by high peaks creating a dramatic alpine atmosphere. The terrain feels quiet and expansive.",
    "final": false
  },
  {
    "id": 14,
    "alt": "Kanarata peak, 2691 m, Rila mountain, Bulgaria",
    "nameBg": "Канарата",
    "nameEn": "Kanarata",
    "height": "2,691 m",
    "duration": "6 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A compact rocky summit with steep sections and strong exposure. The peak feels powerful despite its modest size.",
    "final": false
  },
  {
    "id": 15,
    "alt": "Kioravitsa peak, 2612 m, Rila mountain, Bulgaria",
    "nameBg": "Кьоравица",
    "nameEn": "Kioravitsa",
    "height": "2,612 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A remote-feeling climb with steady ascent through alpine terrain and wide visibility. It offers a calm but persistent effort.",
    "final": false
  },
  {
    "id": 16,
    "alt": "Riletz peak, 2713 m, Rila mountain, Bulgaria",
    "nameBg": "Рилец",
    "nameEn": "Riletz",
    "height": "2,713 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A classic Rila summit with long ridges and wide views across the mountain. The route is steady and rewarding.",
    "final": false
  },
  {
    "id": 17,
    "alt": "Evil Tooth peak, 2678 m, Rila mountain, Bulgaria",
    "nameBg": "Злият зъб",
    "nameEn": "Evil Tooth",
    "height": "2,678 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A sharp limestone formation with dramatic visual presence and short but intense ascent. It stands out strongly in the landscape.",
    "final": false
  },
  {
    "id": 18,
    "alt": "Orlovets peak, 2686 m, Rila mountain, Bulgaria",
    "nameBg": "Орловец",
    "nameEn": "Orlovets",
    "height": "2,686 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A broad summit with iconic views toward Malyovitsa and surrounding peaks. One of the most visually rewarding in the area.",
    "final": false
  },
  {
    "id": 19,
    "alt": "Lovnitsa peak, 2695 m, Rila mountain, Bulgaria",
    "nameBg": "Ловница",
    "nameEn": "Lovnitsa",
    "height": "2,695 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A ridge peak with exposed sections and strong alpine character. The cirque views are continuous and striking.",
    "final": false
  },
  {
    "id": 20,
    "alt": "The Camel peak, 2621 m, Rila mountain, Bulgaria",
    "nameBg": "Камилата",
    "nameEn": "The Camel",
    "height": "2,621 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A uniquely shaped summit with softer contours and a calmer hiking experience. It contrasts with the surrounding technical terrain.",
    "final": false
  },
  {
    "id": 21,
    "alt": "Suha Vapa peak, 2639 m, Rila mountain, Bulgaria",
    "nameBg": "Суха Вапа",
    "nameEn": "Suha Vapa",
    "height": "2,639 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A dry rocky ridge with exposed terrain and minimal vegetation. The environment feels raw and elemental.",
    "final": false
  },
  {
    "id": 22,
    "alt": "Ovcharets peak, 2764 m, Rila mountain, Bulgaria",
    "nameBg": "Овчарец",
    "nameEn": "Ovcharets",
    "height": "2,764 m",
    "duration": "7–8 h",
    "distance": "14 km",
    "elevation": "+1,200 m",
    "summary": "A high open summit with wide visibility over central Rila. The ascent is long but scenic and rewarding.",
    "final": false
  },
  {
    "id": 23,
    "alt": "Eleni Vruh peak, 2654 m, Rila mountain, Bulgaria",
    "nameBg": "Елени връх",
    "nameEn": "Eleni Vruh",
    "height": "2,654 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A rounded peak with balanced ascent and strong panoramic views. It connects key ridge sections across the Rila range.",
    "final": false
  },
  {
    "id": 24,
    "alt": "Malyovitsa peak, 2729 m, Rila mountain, Bulgaria",
    "nameBg": "Мальовица",
    "nameEn": "Malyovitsa",
    "height": "2,729 m",
    "duration": "5–6 h",
    "distance": "10 km",
    "elevation": "+900 m",
    "summary": "An iconic Bulgarian peak with steep granite walls and historic mountaineering routes. The ascent is demanding and deeply memorable.",
    "final": false
  },
  {
    "id": 25,
    "alt": "Maluk Mermer peak, 2702 m, Rila mountain, Bulgaria",
    "nameBg": "Малък Мермер",
    "nameEn": "Maluk Mermer",
    "height": "2,702 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A rugged granite summit with complex terrain and constant exposure. The environment feels immersive and wild.",
    "final": false
  },
  {
    "id": 26,
    "alt": "Goliam Mermer peak, 2725 m, Rila mountain, Bulgaria",
    "nameBg": "Голям Мермер",
    "nameEn": "Goliam Mermer",
    "height": "2,725 m",
    "duration": "6–7 h",
    "distance": "13 km",
    "elevation": "+1,000 m",
    "summary": "A larger continuation of the Mermer ridge with stronger exposure and wide views. The feeling is remote and powerful.",
    "final": false
  },
  {
    "id": 27,
    "alt": "Dodov Vruh peak, 2663 m, Rila mountain, Bulgaria",
    "nameBg": "Додов връх",
    "nameEn": "Dodov Vruh",
    "height": "2,663 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A quieter summit with open slopes and steady ascent. The atmosphere is peaceful and stable.",
    "final": false
  },
  {
    "id": 28,
    "alt": "Damga peak, 2669 m, Rila mountain, Bulgaria",
    "nameBg": "Дамга",
    "nameEn": "Damga",
    "height": "2,669 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A distinctive summit with broad panoramic views over northern Rila. The terrain is open and exposed.",
    "final": false
  },
  {
    "id": 29,
    "alt": "Zelen Kamak peak, 2669 m, Rila mountain, Bulgaria",
    "nameBg": "Зелен камък",
    "nameEn": "Zelen Kamak",
    "height": "2,669 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A scenic ridge blending rock and vegetation in a contrasting alpine environment. The hike is steady and pleasant.",
    "final": false
  },
  {
    "id": 30,
    "alt": "Salonite peak, 2683 m, Rila mountain, Bulgaria",
    "nameBg": "Салоните",
    "nameEn": "Salonite",
    "height": "2,683 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+950 m",
    "summary": "A high ridge section with expansive views and broken terrain. It feels remote and open, marking the midpoint of the challenge.",
    "final": false
  },
  {
    "id": 31,
    "alt": "Mechit peak, 2567 m, Rila mountain, Bulgaria",
    "nameBg": "Мечит",
    "nameEn": "Mechit",
    "height": "2,567 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A prominent peak overlooking Rila valleys with long approaches and strong exposure. The climb is demanding.",
    "final": false
  },
  {
    "id": 32,
    "alt": "Hvoinati peak, 2635 m, Bulgaria",
    "nameBg": "Хвойнати",
    "nameEn": "Hvoinati",
    "height": "2,635 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A transition peak from forest to alpine terrain introducing Pirin's character. The hike is varied and scenic.",
    "final": false
  },
  {
    "id": 33,
    "alt": "Vihren peak, 2914 m, Pirin mountain, Bulgaria",
    "nameBg": "Вихрен",
    "nameEn": "Vihren",
    "height": "2,914 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "The highest peak in Pirin with steep, rocky ascent and iconic status. The summit is one of Bulgaria's most celebrated.",
    "final": false
  },
  {
    "id": 34,
    "alt": "Kutelo peak, 2908 m, Pirin mountain, Bulgaria",
    "nameBg": "Кутело",
    "nameEn": "Kutelo",
    "height": "2,908 m",
    "duration": "7–8 h",
    "distance": "13 km",
    "elevation": "+1,100 m",
    "summary": "A dramatic limestone ridge with exposed scrambling and breathtaking drops. The traverse is highly technical and unforgettable.",
    "final": false
  },
  {
    "id": 35,
    "alt": "Kutelo 2 peak, 2908 m, Pirin mountain, Bulgaria",
    "nameBg": "Кутело II",
    "nameEn": "Kutelo II",
    "height": "2,908 m",
    "duration": "7–8 h",
    "distance": "13 km",
    "elevation": "+1,100 m",
    "summary": "Continuation of the Kutelo ridge with sustained exposure and alpine drama. The views remain constant and intense throughout.",
    "final": false
  },
  {
    "id": 36,
    "alt": "Golyam Polezhan peak, 2851 m, Pirin mountain, Bulgaria",
    "nameBg": "Голям Полежан",
    "nameEn": "Golyam Polezhan",
    "height": "2,851 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A broad summit overlooking Pirin lakes and ridges. The climb is steady and visually rewarding at every step.",
    "final": false
  },
  {
    "id": 37,
    "alt": "Malak Polezhan peak, 2822 m, Pirin mountain, Bulgaria",
    "nameBg": "Малък Полежан",
    "nameEn": "Malak Polezhan",
    "height": "2,822 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A smaller but scenic continuation of the Polezhan ridge. The terrain is open and calm with sweeping Pirin views.",
    "final": false
  },
  {
    "id": 38,
    "alt": "Big Kalin peak, 2800 m, Pirin mountain, Bulgaria",
    "nameBg": "Джангал",
    "nameEn": "Big Kalin",
    "height": "2,800 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A rugged and isolated peak with steep terrain and wild surroundings. The feeling is remote and powerful.",
    "final": false
  },
  {
    "id": 39,
    "alt": "Kozi Vrah peak, 2611 m, Pirin mountain, Bulgaria",
    "nameBg": "Кози връх",
    "nameEn": "Kozi Vrah",
    "height": "2,611 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A lower but scenic peak with forested approaches and soft ridgelines. The ascent is calm and the views gentle.",
    "final": false
  },
  {
    "id": 40,
    "alt": "Mancho peak, 2771 m, Pirin mountain, Bulgaria",
    "nameBg": "Манчо",
    "nameEn": "Mancho",
    "height": "2,771 m",
    "duration": "7–8 h",
    "distance": "14 km",
    "elevation": "+1,200 m",
    "summary": "A remote summit with long approach routes and untouched terrain. The environment feels truly wild and unvisited.",
    "final": false
  },
  {
    "id": 41,
    "alt": "Polezhan peak, 2851 m, Pirin mountain, Bulgaria",
    "nameBg": "Полежан",
    "nameEn": "Polezhan",
    "height": "2,851 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A classic Pirin summit with wide views over lakes and ridges. The climb is steady and consistently rewarding.",
    "final": false
  },
  {
    "id": 42,
    "alt": "Bezbog peak, 2645 m, Pirin mountain, Bulgaria",
    "nameBg": "Безбог",
    "nameEn": "Bezbog",
    "height": "2,645 m",
    "duration": "4–5 h",
    "distance": "9 km",
    "elevation": "+700 m",
    "summary": "A highly accessible peak near Bezbog hut and lake. It offers one of the easiest high alpine viewpoints in the entire challenge.",
    "final": false
  },
  {
    "id": 43,
    "alt": "Malka Todorka peak, 2712 m, Pirin mountain, Bulgaria",
    "nameBg": "Малка Тодорка",
    "nameEn": "Malka Todorka",
    "height": "2,712 m",
    "duration": "6–7 h",
    "distance": "11 km",
    "elevation": "+950 m",
    "summary": "A sharp ridge peak with dramatic views toward surrounding cirques. The ascent is short but steep and demands attention.",
    "final": false
  },
  {
    "id": 44,
    "alt": "Vazela peak, 2620 m, Pirin mountain, Bulgaria",
    "nameBg": "Възела",
    "nameEn": "Vazela",
    "height": "2,620 m",
    "duration": "5–6 h",
    "distance": "10 km",
    "elevation": "+800 m",
    "summary": "A rocky summit with varied terrain and wide alpine visibility. The hike is engaging and open throughout.",
    "final": false
  },
  {
    "id": 45,
    "alt": "Opreno peak, 2641 m, Pirin mountain, Bulgaria",
    "nameBg": "Опрено",
    "nameEn": "Opreno",
    "height": "2,641 m",
    "duration": "5–6 h",
    "distance": "10 km",
    "elevation": "+850 m",
    "summary": "A quiet and lesser-known peak with gentle alpine terrain. It feels remote and peaceful amid the more dramatic surroundings.",
    "final": false
  },
  {
    "id": 46,
    "alt": "Golyam Tipik peak, 2654 m, Pirin mountain, Bulgaria",
    "nameBg": "Голям Типик",
    "nameEn": "Golyam Tipik",
    "height": "2,654 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+850 m",
    "summary": "A rugged summit exposed to wind and broken terrain. The atmosphere is harsh and dramatic, with a raw alpine character.",
    "final": false
  },
  {
    "id": 47,
    "alt": "Muratov Vrah peak, 2669 m, Pirin mountain, Bulgaria",
    "nameBg": "Муратов връх",
    "nameEn": "Muratov Vrah",
    "height": "2,669 m",
    "duration": "5–6 h",
    "distance": "10 km",
    "elevation": "+850 m",
    "summary": "A prominent peak with long ascent routes and wide valley views. The climb is visually rewarding from start to summit.",
    "final": false
  },
  {
    "id": 48,
    "alt": "Donchovi Karauli peak, 2649 m, Pirin mountain, Bulgaria",
    "nameBg": "Дончови караули",
    "nameEn": "Donchovi Karauli",
    "height": "2,649 m",
    "duration": "5–6 h",
    "distance": "10 km",
    "elevation": "+850 m",
    "summary": "A rocky ridge with complex terrain and panoramic exposure. The route feels exploratory and constantly surprising.",
    "final": false
  },
  {
    "id": 49,
    "alt": "Valyavishka Chuka peak, 2669 m, Pirin mountain, Bulgaria",
    "nameBg": "Валявишка чука",
    "nameEn": "Valyavishka Chuka",
    "height": "2,669 m",
    "duration": "6–7 h",
    "distance": "11 km",
    "elevation": "+950 m",
    "summary": "A sharp summit with exposed ridges and continuous views. The terrain is moderately technical and demands care.",
    "final": false
  },
  {
    "id": 50,
    "alt": "Valyavishki Chukar peak, 2670 m, Pirin mountain, Bulgaria",
    "nameBg": "Валявишки чукар",
    "nameEn": "Valyavishki Chukar",
    "height": "2,670 m",
    "duration": "6–7 h",
    "distance": "11 km",
    "elevation": "+950 m",
    "summary": "A continuation ridge with similar exposure and alpine character. The hike is steady and scenic — the final stretch begins.",
    "final": false
  },
  {
    "id": 51,
    "alt": "Momin Dvor peak, 2723 m, Pirin mountain, Bulgaria",
    "nameBg": "Момин двор",
    "nameEn": "Momin Dvor",
    "height": "2,723 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A broad summit with sweeping views over central Pirin. The terrain is open and the climb consistently rewarding.",
    "final": false
  },
  {
    "id": 52,
    "alt": "Kamenishka Kukla peak, 2691 m, Pirin mountain, Bulgaria",
    "nameBg": "Каменишка кукла",
    "nameEn": "Kamenishka Kukla",
    "height": "2,691 m",
    "duration": "6–7 h",
    "distance": "12 km",
    "elevation": "+1,000 m",
    "summary": "A striking rock formation resembling a stone figure on the ridge. The climb is steep and dramatic with unique visual character.",
    "final": false
  },
  {
    "id": 53,
    "alt": "Razlozhki Suhodol peak, 2728 m, Pirin mountain, Bulgaria",
    "nameBg": "Разложки суходол",
    "nameEn": "Razlozhki Suhodol",
    "height": "2,728 m",
    "duration": "7–8 h",
    "distance": "13 km",
    "elevation": "+1,100 m",
    "summary": "A long ridge traverse with continuous alpine exposure. The route feels remote and expansive — pure Pirin wilderness.",
    "final": false
  },
  {
    "id": 54,
    "alt": "Bayuvi Dupki peak, 2820 m, Pirin mountain, Bulgaria",
    "nameBg": "Баюви дупки",
    "nameEn": "Bayuvi Dupki",
    "height": "2,820 m",
    "duration": "7–8 h",
    "distance": "13 km",
    "elevation": "+1,100 m",
    "summary": "A highly technical limestone ridge with exposed scrambling sections. One of the most challenging climbs in the entire Pirin range.",
    "final": false
  },
  {
    "id": 55,
    "alt": "Banski Suhodol peak, 2884 m, Pirin mountain, Bulgaria",
    "nameBg": "Бански суходол",
    "nameEn": "Banski Suhodol",
    "height": "2,884 m",
    "duration": "7–8 h",
    "distance": "14 km",
    "elevation": "+1,200 m",
    "summary": "A dramatic ridge with steep drops and constant exposure. The scenery is exceptional and intense — the penultimate peak.",
    "final": false
  },
  {
    "id": 56,
    "alt": "Musala peak, 2925 m, highest peak in the Balkans, Rila mountain, Bulgaria",
    "nameBg": "Мусала",
    "nameEn": "Musala",
    "height": "2,925 m",
    "duration": "5–6 h",
    "distance": "11 km",
    "elevation": "+900 m",
    "summary": "The highest peak in the Balkans with unmatched panoramic views across Rila. A symbolic and iconic finale — the challenge complete.",
    "final": true
  }
]
;
